export const COURT_NAMES = [
  'CLITECSA',
  'JAFRISUR',
  'DENTAL CLINIC',
  'JOYERIA POSITO',
  'BLANCA IMPRESORES',
  'HACIENDA LA LAGUNA',
  'SERVIMAIN',
  'ESTRELLA DAMM (exterior)',
]

export const MAX_GUESTS_PER_EVENT = 3
